# Generated by Django 5.0.1 on 2024-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_text_languagemodels_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageFileModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='file/')),
                ('pattern', models.CharField(choices=[('latin', 'latin'), ('cyrillic', 'cyrillic')], max_length=20)),
            ],
        ),
    ]
